import SwiftUI
import AppKit

/// Represents an app that can be ignored
struct IgnoredApp: Identifiable, Hashable {
    let id: String // bundle ID
    let name: String
    let icon: NSImage?

    init(bundleId: String, name: String, icon: NSImage?) {
        self.id = bundleId
        self.name = name
        self.icon = icon
    }

    /// Create from a bundle ID by looking up app info
    static func fromBundleId(_ bundleId: String) -> IgnoredApp {
        if let appURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleId),
           let bundle = Bundle(url: appURL) {
            let name = bundle.object(forInfoDictionaryKey: "CFBundleName") as? String
                ?? bundle.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String
                ?? appURL.deletingPathExtension().lastPathComponent
            let icon = NSWorkspace.shared.icon(forFile: appURL.path)
            return IgnoredApp(bundleId: bundleId, name: name, icon: icon)
        }
        // Fallback for apps that can't be found
        return IgnoredApp(bundleId: bundleId, name: bundleId, icon: nil)
    }
}

struct PrivacySettingsView: View {
    @ObservedObject private var settings = AppSettings.shared

    var body: some View {
        Form {
            Section {
                Toggle(isOn: $settings.generateLinkPreviews) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Generate link previews")
                        Text("Download web content for previews; may activate one-time or analytics-sensitive links.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }

            Section {
                Toggle(isOn: $settings.ignoreConfidentialContent) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Ignore confidential content")
                        Text("Do not save passwords and sensitive data when detected.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                Toggle(isOn: $settings.ignoreTransientContent) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Ignore transient content")
                        Text("Do not save temporary data generated by other apps.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }

            Section {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Ignore Applications")
                        .font(.headline)
                    Text("Do not save content copied from the applications below.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(.bottom, 4)

                IgnoredAppsListView()
            }
        }
        .formStyle(.grouped)
    }
}

struct IgnoredAppsListView: View {
    @ObservedObject private var settings = AppSettings.shared
    @State private var ignoredApps: [IgnoredApp] = []

    var body: some View {
        VStack(spacing: 0) {
            // List of ignored apps
            if ignoredApps.isEmpty {
                Text("No applications ignored")
                    .foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity, minHeight: 60)
            } else {
                List {
                    ForEach(ignoredApps) { app in
                        HStack(spacing: 10) {
                            if let icon = app.icon {
                                Image(nsImage: icon)
                                    .resizable()
                                    .frame(width: 24, height: 24)
                            } else {
                                Image(systemName: "app.fill")
                                    .frame(width: 24, height: 24)
                                    .foregroundStyle(.secondary)
                            }
                            Text(app.name)
                            Spacer()
                        }
                        .contentShape(Rectangle())
                    }
                }
                .listStyle(.plain)
                .frame(minHeight: 80, maxHeight: 160)
            }

            Divider()

            // Add/Remove buttons
            HStack(spacing: 0) {
                Button(action: addApp) {
                    Image(systemName: "plus")
                        .frame(width: 24, height: 20)
                }
                .buttonStyle(.borderless)

                Divider()
                    .frame(height: 16)

                Button(action: removeSelectedApp) {
                    Image(systemName: "minus")
                        .frame(width: 24, height: 20)
                }
                .buttonStyle(.borderless)
                .disabled(ignoredApps.isEmpty)

                Spacer()
            }
            .padding(.horizontal, 4)
            .padding(.vertical, 4)
        }
        .background(Color(nsColor: .controlBackgroundColor))
        .cornerRadius(6)
        .overlay(
            RoundedRectangle(cornerRadius: 6)
                .stroke(Color(nsColor: .separatorColor), lineWidth: 1)
        )
        .onAppear {
            refreshIgnoredApps()
        }
        .onChange(of: settings.ignoredAppBundleIds) { _, _ in
            refreshIgnoredApps()
        }
    }

    private func refreshIgnoredApps() {
        ignoredApps = settings.ignoredAppBundleIds
            .map { IgnoredApp.fromBundleId($0) }
            .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    private func addApp() {
        let panel = NSOpenPanel()
        panel.title = "Select Application to Ignore"
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = true
        panel.allowedContentTypes = [.application]
        panel.directoryURL = URL(fileURLWithPath: "/Applications")

        panel.begin { response in
            guard response == .OK else { return }

            for url in panel.urls {
                if let bundle = Bundle(url: url),
                   let bundleId = bundle.bundleIdentifier {
                    settings.addIgnoredApp(bundleId: bundleId)
                }
            }
        }
    }

    private func removeSelectedApp() {
        // Remove the last app if any exist (simple approach)
        // A more sophisticated UI would track selection
        if let lastApp = ignoredApps.last {
            settings.removeIgnoredApp(bundleId: lastApp.id)
        }
    }
}

#Preview {
    PrivacySettingsView()
        .frame(width: 420, height: 400)
}
