// swift-tools-version: 6.2
//
// ┌─────────────────────────────────────────────────────────────────────────────┐
// │ DEPENDENCY MAP - Rust/Swift FFI Integration                                 │
// │                                                                             │
// │ ClipKittyRustFFI (C target):                                                │
// │   sources: ClipKittyRustFFI.c                                               │
// │   headers: clipkitty_coreFFI.h (auto-generated by UniFFI)                   │
// │   library: libclipkitty_core.a (auto-built by generate-bindings)            │
// │                                                                             │
// │ ClipKittyRust (Swift target):                                               │
// │   depends: ClipKittyRustFFI                                                 │
// │   sources: clipkitty_core.swift (auto-generated)                            │
// │            ClipKittyRust.swift (manual extensions)                          │
// │                                                                             │
// │ To regenerate bindings: rust-core/scripts/generate-bindings.sh              │
// │ Source of truth: rust-core/src/clipkitty_core.udl                           │
// └─────────────────────────────────────────────────────────────────────────────┘

import PackageDescription

let package = Package(
    name: "ClipKitty",
    platforms: [
        .macOS(.v15)
    ],
    dependencies: [
        // GRDB used only for FTS integration tests
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.0.0")
    ],
    targets: [
        // Rust Core library FFI bridge
        // SYNC: Library name must match rust-core/Cargo.toml [lib] name = "clipkitty_core"
        // SYNC: Header comes from rust-core/scripts/generate-bindings → clipkitty_coreFFI.h
        .target(
            name: "ClipKittyRustFFI",
            path: "Sources/ClipKittyRust",
            sources: ["ClipKittyRustFFI.c"],
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath(".")
            ],
            linkerSettings: [
                .linkedLibrary("clipkitty_core"),  // → libclipkitty_core.a
                .unsafeFlags(["-L", "Sources/ClipKittyRust"])
            ]
        ),
        // Swift wrapper for Rust core
        // SYNC: clipkitty_core.swift is auto-generated, ClipKittyRust.swift is manual
        .target(
            name: "ClipKittyRust",
            dependencies: ["ClipKittyRustFFI"],
            path: "Sources/ClipKittyRustWrapper"
        ),
        .executableTarget(
            name: "ClipKitty",
            dependencies: [
                "ClipKittyRust"
            ],
            path: "Sources/App",
            resources: [
                .copy("Resources/Fonts"),
                .copy("Resources/menu-bar.svg")
            ],
            swiftSettings: [
                // SANDBOXED flag is set via: swift build -Xswiftc -DSANDBOXED
                // When set, disables paste functionality (sandbox blocks CGEvent posting)
            ]
        ),
        .testTarget(
            name: "ClipKittyTests",
            dependencies: [
                "ClipKittyRust",
                .product(name: "GRDB", package: "GRDB.swift")
            ],
            path: "Tests",
            exclude: ["UITests"]
        )
    ]
)
